import matplotlib.pyplot as plt
import numpy as np
import os
import pickle
from copy import deepcopy
import pandas as pd

def WT_sce_gen(WT_no, samples_no, seed = 0):
    """
    Generate wind forecast and error scenarios from preprocessed historical data.

    The function preserves temporal correlation and non-Gaussian error behavior,
    clips negative generation, and normalizes outputs by the global maximum of
    the full scenario tensor.
    """

    ### step 1, find WT standard curve, i.e., the prototype curve
    WT_forecast = np.load(os.path.join(os.getcwd(), 'data', 'processed', 'GEFC2012_wind_forecast.npy'))  # EN: load prototype forecast
    WT_forecast = WT_forecast.reshape([1, -1, 1])
    WT_forecast = np.tile(WT_forecast, (1, 1, WT_no))

    ## get the WT error
    WT_error_samples = np.load(os.path.join(os.getcwd(), 'data', 'processed', 'GEFC2012_temporal_correlated_error_samples.npy'))  # EN: load error samples
    WT_error_samples = WT_error_samples[:samples_no * WT_no].reshape(samples_no, WT_no, -1)  # EN: reshape to (samples_no, WT_no, T)
    # permute the last two dimensions
    WT_error_samples = np.transpose(WT_error_samples, (0, 2, 1))

    # EN: compose full scenarios and clip negatives to zero (physical constraint: no negative generation)
    WT_samples_full = WT_forecast + WT_error_samples
    ### wind scenarios must be non-negative
    WT_samples_full[WT_samples_full < 0] = 0

    # re_calculate the error
    WT_error_samples = WT_samples_full - WT_forecast

    # normalize to make the maximum generation to be 1
    norm_factor = np.max(WT_samples_full)
    WT_samples_full = WT_samples_full / norm_factor
    WT_error_samples = WT_error_samples / norm_factor
    WT_forecast = WT_forecast / norm_factor

    # check if WT_samples == WT_forecast + WT_error
    if not np.allclose(WT_samples_full, WT_forecast + WT_error_samples):
        raise ValueError('the WT samples are not equal to the sum of forecast and error')

    if np.min(WT_samples_full) < 0:
        raise ValueError('the RES samples have negative generation!!!')

    # EN: return three arrays with aligned shapes for dispatch modeling
    return WT_forecast[0], WT_error_samples, WT_samples_full

def load_sce_gen(num_bus, samples_no, load_bus_size, load_total, T_max=48, seed=0, error_scale=1.0):
    """
    Generate load forecast and error scenarios from the preprocessed Austria dataset.

    The function uses temporally correlated error samples and returns forecast,
    error, and full-scenario tensors for all load buses.
    """
    
    # Step 1: Load preprocessed load forecast prototype curve (first T_max hours)
    data_path = os.path.join(os.getcwd(), 'data', 'raw', 'energy_weather_data.csv')
    df = pd.read_csv(data_path, parse_dates=['datetime'])
    load_forecast_raw = df['AT_load_forecast_entsoe_transparency'].values
    load_actual = df['AT_load_actual_entsoe_transparency'].values
    
    # Remove NaN values
    valid_idx = ~(np.isnan(load_actual) | np.isnan(load_forecast_raw))
    load_forecast_raw = load_forecast_raw[valid_idx]
    load_actual = load_actual[valid_idx]
    
    # Calculate mean load for normalization
    load_mean = np.mean(load_actual)
    load_forecast_norm = load_forecast_raw[:T_max] / load_mean
    load_forecast = load_forecast_norm.reshape([1, -1, 1])  # Reshape to (1, T_max, 1)
    load_forecast = np.tile(load_forecast, (1, 1, num_bus))  # Tile to (1, T_max, num_bus)
    
    # Step 2: Load preprocessed error samples (temporally correlated, generated by load_error_preprocess.py)
    error_samples_path = os.path.join(os.getcwd(), 'data', 'processed', 'load_temporal_correlated_error_samples.npy')
    
    try:
        load_error_samples = np.load(error_samples_path)  # Shape: (20000, 48) - normalized samples
        print(f"✓ Loaded preprocessed load error samples from: {error_samples_path}")
        print(f"  Shape: {load_error_samples.shape}, Data type: {load_error_samples.dtype}")
    except FileNotFoundError:
        raise FileNotFoundError(
            f"\n❌ ERROR: Preprocessed load error file not found!\n"
            f"   Expected path: {error_samples_path}\n"
            f"   Please run: python load_error_preprocess.py\n"
            f"   to generate the file before using load_sce_gen()"
        )
    
    # Step 3: Sample error scenarios from preprocessed samples
    rng = np.random.RandomState(seed)
    n_available = load_error_samples.shape[0]
    
    if samples_no > n_available:
        # If requested samples exceed available, use with replacement
        sample_indices = rng.choice(n_available, samples_no, replace=True)
        print(f"⚠️  Requested {samples_no} samples > available {n_available}, sampling with replacement")
    else:
        # Use without replacement
        sample_indices = rng.choice(n_available, samples_no, replace=False)
    
    load_error_scenarios = load_error_samples[sample_indices]  # Shape: (samples_no, T_max)
    
    # Step 4: Apply error_scale factor to adjust uncertainty magnitude
    load_error_scenarios = load_error_scenarios * error_scale
    
    # Step 5: Distribute errors across buses according to load proportion
    # Map errors from (samples_no, T_max) to (samples_no, T_max, num_bus)
    load_error_samples_full = np.zeros((samples_no, T_max, num_bus))
    
    # Calculate load proportion for each bus
    load_proportions = load_bus_size / load_total  # Shape: (num_bus,)
    
    for bus in range(num_bus):
        # Each bus gets a share of total system error proportional to its load
        load_error_samples_full[:, :, bus] = load_error_scenarios * load_proportions[bus]
    
    print(f"✓ Load error distributed by bus proportion:")
    print(f"  Bus load proportions: {load_proportions}")
    print(f"  System total load: {load_total:.2f} MW")
    
    # Construct full scenarios (forecast + error)
    load_full_samples = load_forecast + load_error_samples_full
    
    # Step 6: Ensure non-negativity (load cannot be negative)
    load_full_samples[load_full_samples < 0] = 0
    
    # Recalculate error after clipping
    load_error_samples_full = load_full_samples - load_forecast
    
    # Step 7: Normalize by global max (SAME logic as WT_sce_gen)
    norm_factor = np.max(load_full_samples)
    if norm_factor > 0:
        load_full_samples = load_full_samples / norm_factor
        load_error_samples_full = load_error_samples_full / norm_factor
        load_forecast = load_forecast / norm_factor
    
    # Consistency check
    if not np.allclose(load_full_samples, load_forecast + load_error_samples_full):
        raise ValueError('Load samples are not equal to the sum of forecast and error')
    
    if np.min(load_full_samples) < 0:
        raise ValueError('Load samples have negative values after normalization!')
    
    # Return: forecast (T_max, num_bus), error (samples_no, T_max, num_bus), full (samples_no, T_max, num_bus)
    # Extract [0] to match WT_sce_gen return format: (T_max, num_bus)
    return load_forecast[0], load_error_samples_full, load_full_samples

if __name__ == '__main__':
    # EN: demo plot — histogram of error samples and sample trajectories for one WT.
    WT_no = 10
    samples_no = 2000
    WT_forecast, WT_error_samples, WT_samples_full = WT_sce_gen(WT_no, samples_no)

    # EN: histogram of errors (flattened), with Gaussian fit overlay for visual reference.
    fig, axs = plt.subplots(2, 1, figsize=(6, 6))
    axs[0].hist(WT_error_samples.flatten(), bins=150, density=True, alpha=0.75, label='error samples')
    # plot the Gaussian fit
    from scipy.stats import norm
    mu, std = np.mean(WT_error_samples.flatten()), np.std(WT_error_samples.flatten())
    x = np.linspace(np.min(WT_error_samples), np.max(WT_error_samples), 100)
    p = norm.pdf(x, mu, std)
    axs[0].plot(x, p, 'r', linewidth=1, label='Gaussian fit')

    axs[0].set_title('WT error samples histgram')
    axs[0].set_xlabel('normalised error')
    axs[0].set_ylabel('frequency')
    axs[0].legend()

    axs[1].plot(WT_samples_full[..., 0].T)
    axs[1].set_title('WT generation samples')
    axs[1].set_xlabel('hour')
    axs[1].set_ylabel('normalised generation')
    axs[1].set_xlim([0, WT_forecast.shape[0] - 1])
    plt.tight_layout()
    plt.show()
